config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: redirect('/games/new_player')

  namespace :games do
    get :clear
    get :new_player
    post :enter_player
    post :drop_player
    get :show
    post :leave_answer
    post :choose_winner_answer
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :player, optional: true
  belongs_to :question, optional: true

  scope :unused, -> { where(question: nil) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  enum role: [:player, :tzar, :random]
  enum status: [:in, :out]

  has_many :answers

  scope :human, -> { where.not(role: :random) }

  def score
    answers.count(&:winner?)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  helper_method :current_player, :current_question, :previous_questions, :missing_answers, :total_answers,
                :current_player_unused_answers, :players, :tzar, :in_players
  after_action :broadcast_action, only: %i(clear enter_player drop_player leave_answer choose_winner_answer)

  def clear
    clear_game
    redirect_to action: :new_player
  end

  def new_player
    redirect_to action: :show if current_player.present?
  end

  def enter_player
    @current_player = Player.find_or_create_by(player_params)
    cookies[:player_id] = current_player.id
    current_player.in!
    draw_answers

    current_player.tzar! if Player.human.count == 1
    start_round if Player.human.count == 2

    redirect_to action: :show
  end

  def drop_player
    current_player.answers.unused.update_all(player_id: nil)
    current_player.player!
    current_player.out!
    @current_player = nil
    cookies[:player_id] = nil

    if Player.human.in.none?
      clear_game
    else
      Player.human.in.first.tzar!
    end

    redirect_to action: :new_player
  end

  def show
    return redirect_to action: :new_player if current_player.blank?
    render 'empty' if Player.human.in.count < 2
  end

  def leave_answer
    answer = Answer.find(params.require(:answer)[:id])
    current_question.answers << answer
    draw_answers
    leave_random_answers if current_question.answers.count == Player.player.count

    redirect_to action: :show
  end

  def choose_winner_answer
    answer = Answer.find(params.require(:answer)[:id])
    answer.update(winner: true)

    unless answer.player.random?
      current_player.player!
      answer.player.tzar!
    end

    start_round

    redirect_to action: :show
  end

  protected

  def start_round
    round_in_progress = current_question.present? && current_question.answers.none?(&:winner?)
    return if round_in_progress
    draw_question
  end

  def draw_question
    previous_round = @current_question.try(:round) || 0
    @current_question = Question.where(round: nil, gaps: 1).all.sample
    @current_question.update(round: previous_round + 1)
  end

  def leave_random_answers
    Player.random.each do |player|
      answer = Answer.where(player_id: nil).all.sample
      answer.update(player: player, question: current_question)
    end
  end

  def draw_answers
    answers_to_draw = 7 - current_player.answers.unused.count
    current_player.answers += Answer.where(player: nil).all.sample(answers_to_draw)
    current_player.save
  end

  def player_params
    params.require(:player).permit(:name)
  end

  def current_player
    @current_player ||= Player.find_by(id: cookies[:player_id])
  end

  def current_question
    @current_question ||= Question.where.not(round: nil).order(:round).last
  end

  def previous_questions
    Question.where.not(id: current_question.id, round: nil).order(round: :desc)
  end

  def missing_answers
    total_answers - current_question.answers.count
  end

  def total_answers
    Player.in.where.not(role: :tzar).count
  end

  def current_player_unused_answers
    current_player.answers.unused.order(:updated_at)
  end

  def broadcast_action
    ActionCable.server.broadcast('game', nil)
  end

  def players
    Player.all.sort_by { |player| -player.score }
  end

  def tzar
    Player.tzar.first
  end

  def in_players
    Player.in
  end

  def clear_game
    Answer.update_all(player_id: nil, question_id: nil)
    Question.update_all(round: nil)
    Player.human.destroy_all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/empty.html.haml
%p
  Jugador: #{current_player.name}.
  #{ link_to 'Salir', games_drop_player_path, method: :post }.

%h3 No hay nadie en la partida. Invita a alguien.

app/views/games/new_player.html.haml
.grid-x
  .small-12.medium-6.medium-offset-3.cell
    %h1 Empieza a jugar
    = form_for(:player, url: games_enter_player_path) do |f|
      = f.text_field :name, placeholder: 'Nombre'
      = f.submit 'Entrar', class: 'button expanded'

    %h2 Jugadores en la partida:
    %ul
    - in_players.each do |player|
      %li #{player.name} #{' (Zar)' if player.tzar?}

app/views/games/show.html.haml
%p
  Jugador: #{current_player.name}.
  #{ button_to 'Salir de la partida', games_drop_player_path, method: :post, class: 'tiny button' }

- current_player_answer = current_question.answers.find_by(player: current_player)
- already_answered = current_player_answer.present?
- must_answer = current_player.player? && current_player_answer.blank?

.card.card--question #{current_question.text}

%p Zar: #{tzar.name}#{ ' (Tú)' if current_player.tzar? }

- unless missing_answers.zero?
  %p Faltan #{missing_answers} de #{total_answers} respuestas
- else
  - current_question.answers.each do |answer|
    .card.card--answer
      = answer.text
      - if current_player.tzar?
        = form_for :answer, url: games_choose_winner_answer_path, method: :post do |f|
          = f.hidden_field :id, value: answer.id
          = f.submit 'Elegir', class: 'button expanded no-margin margin-top'

%h2 Tus respuestas
- current_player_unused_answers.each do |answer|
  .card.card--answer
    = answer.text
    - if must_answer
      = form_for :answer, url: games_leave_answer_path, method: :post do |f|
        = f.hidden_field :id, value: answer.id
        = f.submit 'Usar', class: 'button expanded no-margin margin-top'


%h3 Puntuaciones
%ul
  - max_score = players.map(&:score).max
  - players.each do |player|
    - player_and_score = "#{player.name}: #{player.score}"
    %li
      - if player.score == max_score
        %b= player_and_score
      - else
        = player_and_score

- if previous_questions.any?
  %h3 Preguntas anteriores (#{current_question.round - 1})
  - previous_questions.each do |question|
    .card.card--question= question.text
    - question.answers.order(winner: :desc).each do |answer|
      .card.card--answer
        %span= answer.text
        - if answer.winner?
          %div
            %span.label Ganadora

app/views/layouts/application.html.haml
!!! 5
%html{ lang: 'es' }
  %head
    %meta{ charset: 'utf-8' }

    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }

    %title= content_for?(:title) ? yield(:title) : 'CAH'

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  %body
    .grid-container
      .grid-x.grid-padding-x
        .small-12.cell= yield